


[
    {
        "name": "Intel Core i7-11700K",
        "image": "/images/intel_core_i7_11700k.jpg",
        "description": "Powerful Intel processor for high-performance computing.",
        "category": "64c4edc702a4068f076f54b9",
        "price": 399.99,
        "status": "In Stock",
        "rating": 3.8,
        "featured": true,
    },
    {
        "name": "AMD Ryzen 9 5950X",
        "image": "/images/amd_ryzen_9_5950x.webp",
        "description": "Advanced AMD processor with 16 cores for demanding tasks.",
        "category": "64c4edc702a4068f076f54b9",
        "price": 699.99,
        "status": "In Stock",
        "rating": 4.9,
        "featured": true,
    },
    {
        "name": "Intel Core i5-11600K",
        "image": "/images/intel_core_i5_11600k.jpg",
        "description": "Excellent mid-range CPU for gaming and productivity.",
        "category": "64c4edc702a4068f076f54b9",
        "price": 299.99,
        "status": "In Stock",
        "rating": 2.6,
        "featured": false,
    },
    {
        "name": "AMD Ryzen 5 5600X.jpg",
        "image": "/images/amd_ryzen_5_5600x",
        "description": "Budget-friendly AMD processor with impressive performance.",
        "category": "64c4edc702a4068f076f54b9",
        "price": 249.99,
        "status": "In Stock",
        "rating": 4.5,
        "featured": false,
    },
    {
        "name": "ASUS ROG Strix X570-E",
        "image": "/images/asus_rog_strix_x570e.jpg",
        "description": "High-end gaming motherboard with extensive features.",
        "category": "64c4edc702a4068f076f54b9",
        "price": 299.99,
        "status": "In Stock",
        "rating": 3.7,
        "featured": true,
    },
    {
        "name": "GIGABYTE B550 AORUS Pro",
        "image": "/images/gigabyte_b550_aorus_pro.jpg",
        "description": "Robust AMD motherboard for multitasking and overclocking.",
        "category": "64c4edc702a4068f076f54b9",
        "price": 189.99,
        "status": "In Stock",
        "rating": 4.6,
        "featured": true,
    },
    {
        "name": "MSI MAG B460M Mortar",
        "image": "/images/msi_mag_b460m_mortar.jpg",
        "description": "Compact motherboard with excellent performance and reliability.",
        "category": "64c4edc702a4068f076f54b9",
        "price": 129.99,
        "status": "In Stock",
        "rating": 4.4,
        "featured": false,
    },
    {
        "name": "ASRock B550M-ITX/AC",
        "image": "/images/asrock_b550m_itx_ac.png",
        "description": "Mini-ITX motherboard for small form factor builds.",
        "category": "64c4edc702a4068f076f54b9",
        "price": 159.99,
        "status": "In Stock",
        "rating": 4.5,
        "featured": false,
    },
    {
        "name": "Seasonic Focus GX-550",
        "image": "/images/seasonic_focus_gx550.jpg",
        "description": "Compact 550W power supply with silent operation.",
        "category": "64c4ee0d02a4068f076f54bd",
        "price": 79.99,
        "status": "In Stock",
        "rating": 4.6,
        "featured": false
    },
    {
        "name": "Samsung 970 EVO Plus SSD",
        "image": "/images/samsung_970_evo_plus.webp",
        "description": "High-speed NVMe SSD with reliable performance.",
        "category": "64c4ee3e02a4068f076f54bf",
        "price": 119.99,
        "status": "In Stock",
        "rating": 4.9,
        "featured": true
    },
    {
        "name": "Corsair Vengeance RGB Pro",
        "image": "/images/corsair_vengeance_rgb_pro.png",
        "description": "High-performance DDR4 RAM with customizable RGB lighting.",
        "category": "64c4ede702a4068f076f54bb",
        "price": 89.99,
        "status": "In Stock",
        "rating": 2.7,
        "featured": true
    },
    {
        "name": "Crucial MX500 SSD",
        "image": "/images/crucial_mx500_ssd.png",
        "description": "Reliable SATA SSD for faster boot times and data transfer.",
        "category": "64c4ee3e02a4068f076f54bf",
        "price": 79.99,
        "status": "In Stock",
        "rating": 2.7,
        "featured": false
    },
    {
        "name": "Corsair RM750x",
        "image": "/images/corsair_rm750x.jpg",
        "description": "High-efficiency 750W modular power supply for gaming PCs.",
        "category": "64c4ee0d02a4068f076f54bd",
        "price": 129.99,
        "status": "In Stock",
        "rating": 4.8,
        "featured": true
    },
    {
        "name": "NVIDIA GeForce RTX 3080",
        "image": "/images/nvidia_geforce_rtx_3080.jpg",
        "description": "High-end gaming GPU for ultra-smooth gameplay.",
        "category": "64c4ee9f02a4068f076f54c3",
        "price": 899.99,
        "status": "In Stock",
        "rating": 4.9,
        "featured": true
    },
    {
        "name": "Kingston HyperX Fury",
        "image": "/images/kingston_hyperx_fury.jpg",
        "description": "Affordable and fast DDR4 RAM for gaming and productivity.",
        "category": "64c4ede702a4068f076f54bb",
        "price": 49.99,
        "status": "In Stock",
        "rating": 3.5,
        "featured": false
    },
    {
        "name": "Crucial Ballistix RGB",
        "image": "/images/crucial_ballistix_rgb.jpg",
        "description": "Stylish DDR4 RAM with integrated RGB lighting.",
        "category": "64c4ede702a4068f076f54bb",
        "price": 79.99,
        "status": "In Stock",
        "rating": 4.4,
        "featured": false
    },
    {
        "name": "EVGA SuperNOVA 650 G5",
        "image": "/images/evga_supernova_650_g5.png",
        "description": "Reliable 650W power supply with Gold efficiency rating.",
        "category": "64c4ee0d02a4068f076f54bd",
        "price": 99.99,
        "status": "In Stock",
        "rating": 4.7,
        "featured": true
    },
    {
        "name": "Western Digital Blue HDD",
        "image": "/images/wd_blue_hdd.jpg",
        "description": "Spacious 1TB HDD for mass storage and backups.",
        "category": "64c4ee3e02a4068f076f54bf",
        "price": 49.99,
        "status": "In Stock",
        "rating": 3.6,
        "featured": true
    },
    {
        "name": "ASUS ROG Swift PG279Q",
        "image": "/images/asus_rog_swift_pg279q.jpg",
        "description": "27-inch 1440p gaming monitor with high refresh rate.",
        "category": "64c4ee6b02a4068f076f54c1",
        "price": 599.99,
        "status": "In Stock",
        "rating": 4.8,
        "featured": true
    },
    {
        "name": "Seagate BarraCuda 2TB",
        "image": "/images/seagate_barracuda_hdd.png",
        "description": "Large capacity HDD for multimedia storage.",
        "category": "64c4ee3e02a4068f076f54bf",
        "price": 69.99,
        "status": "In Stock",
        "rating": 2.5,
        "featured": false
    },
    {
        "name": "AMD Radeon RX 6800 XT",
        "image": "/images/amd_radeon_rx_6800_xt.jpeg",
        "description": "Top-tier AMD GPU with excellent ray tracing performance.",
        "category": "64c4ee9f02a4068f076f54c3",
        "price": 799.99,
        "status": "In Stock",
        "rating": 4.8,
        "featured": true
    },
    {
        "name": "Cooler Master MWE 750",
        "image": "/images/cooler_master_mwe_750.jpg",
        "description": "Budget-friendly 750W power supply for mainstream systems.",
        "category": "64c4ee0d02a4068f076f54bd",
        "price": 69.99,
        "status": "In Stock",
        "rating": 4.5,
        "featured": false
    },
    {
        "name": "Acer R240HY",
        "image": "/images/acer_r240hy",
        "description": "Affordable 23.8-inch monitor for everyday use.",
        "category": "64c4ee6b02a4068f076f54c1",
        "price": 129.99,
        "status": "In Stock",
        "rating": 4.5,
        "featured": false
    },
    {
        "name": "Dell Ultrasharp U2419H",
        "image": "/images/dell_ultrasharp_u2419h.jpg",
        "description": "24-inch IPS monitor for color-accurate work.",
        "category": "64c4ee6b02a4068f076f54c1",
        "price": 249.99,
        "status": "In Stock",
        "rating": 4.6,
        "featured": true
    },
    {
        "name": "LG 34UC79G-B",
        "image": "/images/lg_34uc79g_b",
        "description": "34-inch ultrawide monitor for immersive gaming.",
        "category": "64c4ee6b02a4068f076f54c1",
        "price": 399.99,
        "status": "In Stock",
        "rating": 4.7,
        "featured": false
    },
    {
        "name": "G.SKILL Ripjaws V",
        "image": "/images/gskill_ripjaws_v.png",
        "description": "Reliable DDR4 memory for smooth multitasking.",
        "category": "64c4ede702a4068f076f54bb",
        "price": 69.99,
        "status": "In Stock",
        "rating": 4.6,
        "featured": true
    },
    {
        "name": "NVIDIA GeForce GTX 1660 Super",
        "image": "/images/nvidia_geforce_gtx_1660_super",
        "description": "Budget-friendly GPU for 1080p gaming.",
        "category": "64c4ee9f02a4068f076f54c3",
        "price": 299.99,
        "status": "In Stock",
        "rating": 4.6,
        "featured": false
    },
    {
        "name": "AMD Radeon RX 6700 XT",
        "image": "/images/amd_radeon_rx_6700_xt",
        "description": "Mid-range AMD GPU with great performance per dollar.",
        "category": "64c4ee9f02a4068f076f54c3",
        "price": 449.99,
        "status": "In Stock",
        "rating": 4.7,
        "featured": false
    }
]